import os
from setuptools import setup
import setuptools_scm


scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""


def local_scheme(version):
    sal_version = (
        os.environ.get("TS_SAL_VERSION", "0")
        .strip("v")
        .replace("pre", "")
        .split("_")[0]
    )
    xml_version = os.environ.get("TS_XML_VERSION", "0").strip("v")

    hash = [f"{int(v):02}" for v in f"{xml_version}.{sal_version}".split(".")]
    hash_str = ""
    for h in hash:
        hash_str += h
    return hash_str


setup(
    version=setuptools_scm.get_version(),
    use_scm_version={
        "write_to": "python/lsst/ts/idl/version.py",
        "write_to_template": scm_version_template,
        "local_scheme": local_scheme,
    },
    package_data={
        "": ["*.idl"],
    },
)
