{% set data= load_setup_py_data() %}
package:
  name: ts-idl
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  skip: False #[win]
  string: {{ TS_XML_VERSION }}_{{ TS_SAL_VERSION }}

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - ts-xml >19
  build:
    - python
    - setuptools_scm
    - setuptools
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-xml >19
